### ISSUE TITLE
Improve object search

### ISSUE THREAD

**Issue by luxaritas** [Xiphoseer/lu-explorer#1]
It's extremely difficult to find items right now, likely because it's searching against the locale table (which seems to not even have entries for a bunch of things?)

Also, case insensitivity would probably be smart. I'll also throw out the idea of using AND as a special keyword to specify two substrings that may not be next to each other

**Comment by Xiphoseer** [comment]
TODO: Investigate using <https://www.npmjs.com/package/flexsearch>
