### ISSUE TITLE
Content-Based titles

### ISSUE THREAD

**Issue by SimonNitzsche** [Xiphoseer/lu-explorer#20]
![image](https://user-images.githubusercontent.com/6717311/99450393-01747100-2921-11eb-9d91-fad62710e180.png)

**Comment by Xiphoseer** [comment]
Added a first iteration of this. Now every route template has a unique name. I'll leave this issue open as a reminder to add IDs/path values at some point too

**Comment by Xiphoseer** [comment]
This should mostly work now
