### ISSUE TITLE
Feature request: mission / achievement distinction in mission list view

### ISSUE THREAD

**Issue by lcdr** [Xiphoseer/lu-explorer#34]
Right now the mission list view only displays mission ID and name, it would be helpful if it also showed whether the mission is a true mission or an achievement, or if there were separate groups for each.

Even cooler but optional would be to replicate the client's passport UI entirely.

**Comment by Xiphoseer** [comment]
> Right now the mission list view only displays mission ID and name, it would be helpful if it also showed whether the mission is a true mission or an achievement, or if there were separate groups for each.

Right, that would be nice. The current dataset for that view is a single json file (<https://xiphoseer.github.io/lu-json/tables/Missions/groupBy/type.json>) that doesn't have that data. Do you think it's better to replace the array for every type with a `{ 'missions': […], 'achievements': […] }` object or to add a new file that just has the set of mission IDs and the set of achievement IDs an could be used elsewhere?

> Even cooler but optional would be to replicate the client's passport UI entirely.

I strongly agree 😄

**Comment by lcdr** [comment]
Well I don't know much about the internals of the webapp so I'm not sure, for this feature alone I think `{ 'missions': […], 'achievements': […] }` would work better; grouping them instead of adding another column would be nicer I think, and it's closer to the original UI.
