### ISSUE TITLE
Prismatic Colors

### ISSUE THREAD

**Issue by MasterTemple** [Xiphoseer/lu-explorer#36]
https://lu-explorer.web.app/objects/12101/11
color1 value is empty but its value is 32766 (this is prismatic)

**Comment by Xiphoseer** [comment]
Ok, so prismatic is a special case, because it doesn't appear in <https://lu-explorer.web.app/misc/brick-colors> and I know that it has a special role in rendering. What would you expect LU-Explorer to do? Just display the ID and acknowledge that it can't find the color?

**Comment by Xiphoseer** [comment]
Ok, noticed that prismatic/mosaic (32766) is basically `i16::MAX - 1` so I just pushed an update that displays that as `M-1` and any other invalid value (which are all < 200) as their numeric value.

**Comment by Xiphoseer** [comment]
Closed by df9e305
